from django.db import connections
from pathlib import Path
from .helpers import *
from Bio.Seq import Seq


BASE_DIR = Path(__file__).resolve().parent.parent # goes up from api/
TASKS_DIR = BASE_DIR / "tasks"
RESOURCES_DIR = BASE_DIR / "resources"

FEATURES_MAP = {'core protein':'Core',
                    'envelope protein E1': 'E1',
                    'envelope protein E2':'E2',
                    'RNA-dependent RNA polymerase NS5B':'NS5B',
                    'nonstructural protein NS5A':'NS5A',
                    'nonstructural protein NS4B':'NS4B',
                    'nonstructural protein NS4A':'NS4A',
                    'protease/helicase protein NS3':'NS3',
                    'nonstructural protein NS2':'NS2',
                    'protein p7':'p7'
                  }

def translate_sequence(sub_seq):
    
    clean_seq = sub_seq.replace("-", "N")
    protein = str(Seq(clean_seq).translate(to_stop=False))

    return protein


def drug_analysis(alignment, features):


    known_mutations = []
    present_mutations = []
    final_mutations = []
    drug_regimen_results = []
    # alignment = "----------------------------------------------------------------------GAAAGCGTCTAGCCATGGCGTTAGTACGAGTGTCGTGCAGCCTCCAGGACCCCCCCTCCCGGGAGAGCCATAGTGGTCTGCGGAACCGGTGAGTACACCGGAATCGCTGGGGTGACCGGGTCCTTTCTTGGAGTAACCCGCTCAATACCCAGAAATTTGGGCGTGCCCCCGCGAGATCACTAGCCGAGTAGTGTTGGGTCGCGAAAGGCCTTGTGGTACTGCCTGATAGGGTGCTTGCGAGTGCCCCGGGGGGTCTCGTAGACCGTGCAACATGAGCACACTTCCTAAACCTCAAAGAAAAACCAAAAGAAACACCATCCGTCGCCCACAGGACGTTAAGTTCCCGGGTGGCGGACAGATCGTTGGTGGAGTATACGTGTTGCCGCGCAGGGGCCCACGATTGGGTGTGCGCGCAACGCGTAAAACTTCTGAACGGTCACAGCCTCGCGGACGGCGACAGCCTATCCCCAAGGCGCGTCGGAGCGAAGGCCGGTCCTGGGCTCAGCCCGGGTACCCTTGGCCCCTCTATGGTAACGAGGGTTGCGGGTGGGCAGGGTGGCTCCTGTCCCCACGCGGCTCCCGTCCATCTTGGGGCCCAAATGACCCTCGGCGAAGGTCCCGCAATTTGGGTAAAGTCATCGATACCCTCACGTGCGGATTCGCCGACCTCATGGGGTACATCCCGCTCGTCGGCGCTCCCGTTGGAGGCGTCGCAAGAGCCCTCGCGCATGGCGTGAGGGCCCTTGAGGACGGGATAAATTTTGCAACAGGGAACTTACCCGGTTGCTCCTTTTCTATCTTCCTTCTTGCTCTATTTTCTTGCTTAATTCATCCAGCGCTAGTTTA--GAGTGCGGAATACGTCTGGTCTCTACGTCCTTACCAACGACTGTTCCAATAGCAGTATTGTGTATGAGGCCGATGACGTTATTCTGCACACACCTGGCTGTGTGCCTTGTGTCCATGGGGGTAATACATCTGAGTGCTGGGACCCAGTGACACCTACAGTGGCAGTCAAGTATG------TCGGAGCAACACCGCTTCGAAGTCATGTAGACCTGCTAGTAGGCGCGGCCACAATGTGCTCCGCGCTCTACGTGGGTGATATGTGCGGGGCCGTCTTCCTCGTGGGACAAGCCTTCACTTTCAGACCCCGTCGCCATCAAACGGTCCAGACCTGTAACTGCTCATTGTACCCAGGCCATCTAACAGGCCATCGAATGGCTTGGGATATGATGATGAATTGGTCCCCTGCTGTGGGTATGGTGGTAGCGCACGTCCTGCGCCTGCCCCAGACCTTGTTCGACATAATAGCCGGGGCCCATTGGGGCATCTTGGCGGGCCTAGCCTATTACTCCATGCAGGGCAACTGGGCCAAAGTCACTATCATCATGGTTATGTTTTCAGGGGTCGATGCCAATACACGTACCACCGGTGGCGCTGCAGCTTTTACCACACGCGGGTTCG-TCGGCTTGTTACC-AAGGCTCCAGACAGAACCTGCAGTTGATCAACACCAATGGCTCGTGGCACATCAATCGTACTGCTCTGAACTGCAATGAGTCCATAAACACAGGGTTTATAGCTGGGTTGATTTATCATCACAAGTTCAACTCTACTGGATGTCCCCAAAGGCTTAGCAGCTGCAAACCCATCACTGCCTTTAGGCAGGGGTGGGGTCCTGACAG--ACGCCAACATCACCGGTCTTGATAACAAACCGTACTGCTGGCACTACGCACCTAAACCTTGTAAAACTGTCCCAGCATCAGATGTCTGCGGCCCCGTGTATTGCTTCACACCGTCGCCAGTGGTTGTAGGCACTACTGATAA---GGGTGTCCCAACCTACACCTGGGGTGGAAATGAGACAGATGTGTTCCTGCTGGAGTCCCTGCGGCCTCCCGGTGGTCGGTGGTTGGGGTGCACGTGGATGAACTCCACGGGGTTTGTCAAGACGTGCGGAGCT-CCCCTTGCGACATCGGGGGTACGGGGAA-CTCACGGTGTTCTGCCCCACCGACTGCTTCAGGAAACATCCTGAGGCCACATACAGCCGGTGTGGTGCGGGGCCTTGGTTAACACCTCGATGCATGGTCGACTACCCATACCGACTTTGGCATTACCCATGTACAGTTAATTTCACATTGTTCAAGGTGAGGATGTTTGTGGGTGGGTTTGAGCACCGGTTTGACGCCGCCTGCCACTGGGCCAGGGGGGAGCGCTGCGATATCGAGGACCGTGATCGCAGCGAGCAGCACCCGCTGCTGCATTCAACGACCGAGTGCTA--TACTGCCTTGCTCCTTTGCACCTATGCCTGCATTGTCAACAGGTCTAATACACCTCCACCAAAACATCGTGGATGTCCAATACCTTTATGGTGTTGGATCTGGCATGGTGGGATGGGCTTTGAAATGGGAATTCGTTGTCCTCGTGTTCCTCCTCCTAGCAGACGCACGCGTGTGCGTTGCCCTTTGGCTGATGCTGATGATATCACAAGCAGAAGCAGCCTTGGAGAACCTTGTCACGCTGAACGC--CATCGCCGGCCGGGACGCATGGTTTCGGCTGGTACCTGGTAGTTTTTTGCGCGGCATGGCATGTGCGGGGTAAACTTGTCCCGCTGGTGACCTACGCCT--GACGGGCTTTGGTCCCTAGCATTGCTCGTCCTCTTGCTCCCCCACCGAGCGTATGC-TTGGTC-AGGTGAAGACAGCGTCTCGTGGGATCTTGGTCCTTTTCGGGTT------CTTTACCTTATCACCTTGGTATAAGCATTGGATCGGTCGCCTCATGTGGTGGAACCAGTA------CACCATAGTAGATGCGGCCCTCCAAGTGTGGGGTCCCCCCCCCCTGGCNCGCGGGGGCGGGGAGGGTGGGGTCCGGGTCAAGCGTGCTTT--ACCCGTCTTTAATTTTTGACATCACTAAGCTGCTGATAGCAATACT-GGGGCCATT---ATACTTCAGGCAGCCATCACTACCACCCCCTATTTTGTGCGTGCACATGTACTGGTCCGCCTTTGCTTGTTCCGCCCCGTAATG---GGGGGGAAATACTTCCAGATG---ATCAT--ACTGAG-------CATTGGCACCTACCTATATGACCACCTGGCGCCAATGCAACATTGGGC-CGCAGCGGCCTTAAAGATCTAGCAGTGGCCACTGAACCTGTAATATTGTCCT--ATGGAAATCAAAGTCATCACCTGGGGCGCGGATACAGCAGCTTGCGGAGATATTCTTTGCGGGCTACCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN-------NNNNNNNNNNNNNNNNNNNNCCCCGATCACAGCATACGCCCAGCAGACTAGAGGCCTTCTTGGGACTATTGTGACCAGCTTGACTGGCAGGGATAAGAACGTGGTGACCGGTGAAGTGCAGGTGCTTTCTACGGCTACCCAGACCTTCCT----AGGTACGACAGTGGGGTTATGTGGACTGTCTACCATGGTGCAGGTTCAAGGACACTTGCGGGCGTTAAACATCCTGCGCTCCAAATGTACACAAATGTAGATCAGGATCTCGTTGGGTGGCCAGCCCCTCCAGGGGCTAAGTCCTTGA-ACCGTGCACCTGCGGGTCTGCAGACTTATACTTGGTTACCCGCGACGCTGATGTCATCCCTGCTCGGCGCAGGGGCGACTCCACAGCGAGCTTGCTCAGTCCTAGACCTCTCGCCTGCCTCAAAGGTTCCTCTGGAGGTCCTGTTATGTGCCCTTCGGGGCATGTCGCGGGGATCTTTAGGGCTGCTGTGTGCACCAGAGGTGTAGCAAAAACCCTACAGTTCATACCAGTGGAAACCCTAG---CACGCAGGAGGTCTCCATCTTTTTCTGATAATTCAACTCCTCCTGCCGTCCCACAGAGCTATCAAGTAGGGTACCTTCATGCCCCGACCGGCAGTGGTAAGAGCACAAAGGTTCCGGCCGCTTATGTAGCACAAGGATATAATGTTCTCGTGTTAAATCCATCAGTGGCGGCCACATTAGGCTTCGGCTCTTACATGTCGCGTGCCTATGGAATTGACCCCAACATCCGCACTGGGAACCGCACCGTTACAACTGG-TGCTAAATGACCTATTCCACCTACGGTAAGTTTCTCGCGGCCGGGGGTTGCTCCGGGGGAGCATATGATGTGATCATCTGTGATGAATGTCATGCCCAAGACGCTACTAGCATATTGGGTATAGGCACGGTCTTGGATCAGGCTGAGACAGCTGGGGTGAGGCTGACGGTTTTGGCGACGGCGACTCCCCCAGGCAGCATAACTGTGCCACATTCTAACATCGAGGAAGTGGCCCTGGGCTCTGAAGGTGAGATCCCTTTCTACGGCAAGGCTATACCGATAGCCCAGGTCAAGGGGGGGAGGCATCTCATCTTTTGTCAATCCAAGAAAAAATGTGATGAGATAGCATCCAAACTAGAGGTATGGGGC-TCAACGCTGTAGCGTACTACAGGGGTCTTGATGTATCCGTCATACCAACAGCAGGAGACGTCGT-GGTTGCGCTACTGATGCCCTCATGACTGGATTCACCGGAGACTTCGACTCTGTCATAGACTGCAACGTGGCTGTTGAGCAGTACGTTGACTTCAGCCTGGACCCCACCTTTTTTATTGAGACTCGCACGCC-CCCCAAGACGCGGTCTCCCGCAGCCAACGTCGTGGTCGTACGGGCCGAGGTAGACTCGGTACGTACCGCTATGTCGCCCCGGGTGAGAGACCGTCTGGAATGTTTGACTCGGTCGTTCTCTGTGAGTGCTATGACACGGGCTGCTCGTGGTACGATCTGCAGCCTGCTGAGACCACAGTCAGACTAAGAGCTTACTTGTCCACGCCGGGGCTACCTGTTTGCCAAGGGCCATTAGACTTTTGGGAGAGCGTCTTCACTGGACTAACTCACATAGATGCCCATTTTCTGTCACAGACTAAGCAGCAGGGACTCAACTTCTCATACCTGACTGCCTACCAAGCCACTGTGTGTGCCCGCGCGCAGGCTCCTCCCCCAAGTTGGGACGAGATGTGGAAATGTCTTGTGCGGCTTAAGCCAACACTACATGGACCTACGCCCCTTCTATACCGGTTGGGGCCTGTCCAAAATGAAATCTGCTCGACACACCCTGTCACAAAATACGTCATGGCATGCATGTCAGCTGATTTGGAAGTAACCACCAGCACCTGGGTGTTGCTTGGAGGGGTCCTCGCAGCCCTAGCGGCCTACTGCTTGTCAGTTGGCTGCGTTGTGATTGTGNNNNNNNATGAGCTGG-GGGCAAGCCAGCACTCGTTCCAGACAAAGAAGTGTTGTACCAGCAATACGATGAGATGGAGGAGTGTTCGCAACCCGCCCCGTACATCGAACAAGCTCAGATAATAGCCCACCAGTTCAAAGAGAAAGTCCTTGGATTGCTGCAGCGAGCCACCCAGCAACAAGCTGTCATTGAGCCCATAGTAGTTACCAACTGGCAGAAGCTTGAGGCCTTTTGGCACAAGCATATGTGGAACTTTGTGAGCGGGATCCAGTATCTAGCAGGCCTCTCCACTTTGCCTGGCAACCCTGCCGTGGCGTCTCTTATGGCGTTCACTGCTTCAGTCACTAGTCCCCTGACGACCAACCAGACTATTGTTTTTAACATACTCGGGGGGGGGGTTGCTACCCATTTGGCGGGCCCCAGAGCTCTT-CCGCATTCGTGGTAAGCGGTTTGGCCGGCGCTGCCATAGGGGGTATAGGCCTGGGCAGGGTCTTGCTTGACATCCTAGCAGGGTACGGAGCTGGTGTCTCAGGCGCCTTGGTAGCTTTTAAGATCATGGGAGGAGAATTCCCCACCGCTGAGGACATGGTCAACCTATTGCCCGCCATACTATCTCCGGGCGCCCTCGTCGTCGGTGTGATATGCGCCGCTATACTACGTCGGCACGTAGGACCTGGGGGGGAGGCGGTGCAGTGGATGAATAGGCTTATTGCATTCGCATCCCGGGGTAACCATGTCTCACCAACACACTATGTCCCCGAGAGCGATGCCGCAGCGAGGGTCACTGCATTGCTGAGTTCTCTAACTGTCACAAGTCTGCTTCGGCGGTTACACCAGTGGATCA--ATGAAGACTAC----CCAAGTCCTTGCAGTTGGCTGCGTACCATCTGGGACTGGGTTTGCATGGTGTTGTCTGACTTCAAGACATGGCTCTCTGCTAAAATCATGCCAGCGCTCCCCGGCCTGCCCTTCATTTCTTGTCAGAAGGGGTACAAGGGCGTATGGCGGGGGAACGGTGTGATGTCAACACGCTGTCCTTGCGGGGCATTGATAGCCGGTCATGTGAAGAATGGGTCCATGCGGCTTGCAGGGCCGCGTACATGTGCTAACATGTGGTACGGCACTTTCCCCATCAATGAGCACACCACCGGACCTAGCACACCTTGCCCACCACCCAACTACACTCGCGCACTATGGCGCGTGGCTGCCAACAGCTACGTTGAGGTGCGTCGGGTGGGGGACTTCCATTACATTACGGG---GGCCACAGAAGATCTCAAATGTCCGTGCCAAGTGCCGGCTGCTGAGTTCTTTACTGAAGTAGATGGGGTGAGGCTCCACCGTTACGCCCCTCCATGTAAGCCCCTGTTAAGGGATGA--AATCATTCGTGGTAGGGTTGAATTCCTACGCGATAGGATCTCAACTCCCTTGTGAACCTGAACCAGATGTTTCTGTACTGACCTCGATGTTGAGAGACCCCTCCCATACCCCCGCCGAGACGGCAGCACGCCGCCTTGCGCGTGGGTCCCCTCCATCGGAGGCGAGCTCATCCCGCAGCCAACTGTCGGCTCCGTCGTGCAGGGCCACTTGC-CAGACGCATAGGCCTCTCCAGACGCTGAGCTAGTAGATGCCAACTTGTTATGGCGGCAAGAGATGGGCAGCAACATTACACGGGTGGAGTCTGAAACAAAGGTTGTGATCCTTGATTCATTCGAACCTCTGAGGGCCGAAACTGATGATGCCGAGCTCTCGGTGGCTGCAGAGTGTTTCAAGAAACCTCCTAAGTATCCTCCAGCCCTTCCTATCTGGGCCAGGCCAGATTACAACCCTCCACTGTTGGACCGCTGGAAAGCACCGGATTATGTACCACCAACTGTCCATGGATGCGCCTTACCACCACGGGGCGCTCCACCGGTGCCTCCCCCCCGGAGGAAGAGGAAAATTCACCAGGATGGTTCCAATGTGTCCGCGGCACTAGCCGCGCTGGC--GGAGAAGTCATTCCCG-TCCTCAACCGCGGGAA--------GAGAATAGCTCATCATTCACACAGTCCAGCACTACTAGGTGCCCCCCCGAGTCCGACTCAGAGTCATGCTCGTCCATGCCTCCTCTCGAGGGGGAGCCGGGCGATCCCGACTTGAGTTGTGACTCTTGGTCCACCGTTAGT---------GACAGCGAGGATGTAGTCTGCTGCTCTATGTCGTACTCTTGGACCGGCGCCTTAGTGACACCATGCAGTGCTGAGGAGGAGAAACTGCCCATTAGTCCACTCAGCAACTCTCTGTTAAGACATCATAACCTAGTCTATTCAACGTCGTCTAGAAGCGCTTCTCAGCGTCAGAAGAAGGTTACCTTCGACAGGCTGCAGGTGCTCGACGACCATTACAAGACTGCATTAAAGGAGGT-AAAGGAGCGGCGTCTGGGGTAAAGGCTCGCATGCTCACCATTGAGGAAGCGTGCCAGCTCGTCCCTCCTCACTCTGCCCGTTCGAAGTTCGGGTATAGTGCGAAAGACGTTCGCT-CCTTGCCAGCAGGGCCATTAACCAGATCCGCTCCGTCTGGGAGGACTTGCTGGAAGACACCACAACCCCAATTCCAACCACCATCATGGCAAAGAACGAGGTGTTTTGCGTAGACCCCGCTAAGGGGGGCCGCAAGCCCGCTCGCCTCATTGTATACCCTGACCTGGGGGTGCGTGTCTGTGAGAAACGCGCCCTGTATGACGTGATACAGAAGTTGTCAATTGCGGCGATGGGTTCTGCCTATGGATTCCAATATTCGCCTCAGCAGCGGGTCGAACGTCTGTTGACGATGTGGACCTCGAAGAAAACCCCCTTGGGGTTCTCGTATGACACCCGCTGCTTTGACTCGACTGTCACTGAACAGGACATTAGGGTAGAAGAGGAGATATACCAATGCTGTAACCTTGAACCGGAGGCCAGGAAAGTGATCTCCTCCCTCACGGAGCGGCTTTACTGCGGGGGCCCTATGTTTAACAGCAAGGGGGCCCAGTGTGGTTATCGCCGCTGCCGTGCTAGCGGAGTTTTGCCTACCAGCTTCGGCAACACAATCACTTGTTACATCAAGGCCACAGC-GGCTGCAAGGCCGCAGGCCTCCGGAACCCGGACTTCCTTGTCTGCGGAGACGATCTAGTCGTGGTAGCTGAGAGTGATGGCGTCGACGAGGATAGAGCAGCCCTGAGAGCTTTCACGGAAGCTATGACCAGGTACTCTGCTCCACCTGGAGATGCTCCACAGCCTACCTACGACCTTGAGCTCATTACATCTTGCTCCTCTAACGTCTCCGTGGCACGAGACAACAAGGGTAAGAGGTACTATTACCTCACCCGTGATGCTACTACTCCCCTGGCCCGCGCGGCTTGGGAAACAGCTCGTCACACTCCAGTTAACTCCTGGTTGGGCAACATCATCATGTACGCGCCTACCATCTGGGTGCGCATGGTAATGATGACACATTTTTTCTCCATACTCCAATCCCAGGAGATACTTGATCGGCCCCTTGACTTTGAAATGTACGGGGCCACTTACTCTGTCACTCCGCTGGATTTACCAGCAATCATTGAAAGACTCCATGGTCTAAGCGCGTTCACGCTCCATAGTTACTCTCCAGTAGAGCTCAATAGGGTTGCGGGGACACTCAGAAAGCTTGGGTGCCCCCCCCTACGAGCTTGGAGACATCGGGCAC-GAGCGTGCGCGCCAAGCTTATGCCCAG-GGAGGAAAGGCCAAAATATGCGGCCTTTATCTCTTTAATTGGGCGGTACGCACCAAGACCAATCTCACTCCATTGCCAGCCGCTGGCCAGTTGGATTTATCCAGTTGGTTTACGGTTGGCGTCGGCGGGAACGACATTTATCACAGCGTGTC---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"

    for feature in features:
        cds_start = 6258
        cds_end = 7601
        cds_start = int(feature["cds_start"])
        cds_end = int(feature["cds_end"])
        clean_feature = FEATURES_MAP[feature['product']]
        sub_seq = alignment[cds_start-1: cds_end-1]
        protein_seq = translate_sequence(sub_seq)
        # print("PROTEIN ", protein)
        with connections["HCV"].cursor() as cursor:
            cursor.execute("""SELECT * 
                                FROM mutation_catalog
                                WHERE protein_name = %s
                            """, [clean_feature])

            mutations = dictfetchall(cursor)

            phdr_alignment_ras_ids = [item["id"] for item in mutations]
            placeholders = ', '.join(['%s'] * len(phdr_alignment_ras_ids))
            query = f""" SELECT dr.id, dr.phdr_alignment_ras_drug_id, rr.phdr_regimen_id, rt.phdr_clinical_trial_id, rt.trial_display_name, rt.trial_nct_id
                        FROM drug_regimen dr
                        LEFT JOIN result_regimen rr on rr.phdr_in_vivo_result_id = dr.id
                        LEFT JOIN result_trial rt ON rt.phdr_in_vivo_result_id = dr.id
                        WHERE dr.phdr_alignment_ras_drug_id IN ({placeholders})
                    """
        
            drug_regimen_results.extend(fetch_all(cursor, query, phdr_alignment_ras_ids))
            # final_mutations.append(mutations)
        for mutation in mutations:
            signature_id = mutation["signature_id"]

            protein, signature = signature_id.split(':')

            single_signature = signature.split('+')
            combination = True

            for ss in single_signature:
                if(ss in known_mutations):
                    continue

                aa = ss[-1]
                if "de" in ss[:-1]:
                    combination = False
                    continue
                    
                aa_idx = int(ss[:-1])

                if aa_idx < 1 or aa_idx > len(protein_seq):
                    continue

                query_aa = protein_seq[aa_idx-1]
                if (query_aa == aa):
                    known_mutations.append(ss)
                else:
                    combination = False

            if combination:
                
                if mutation["id"] not in present_mutations:
                    final_mutations.append(mutation)
                    present_mutations.append(mutation["id"])
                # if signature_id not in present_mutations:
                #     present_mutations.append(signature_id)
                #     final_mutations.append(mutation)


    
    return {"mutations":final_mutations, "drug_regimen_results": drug_regimen_results} 
